In [36]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [5]:
iris_dataset = load_iris()
print("Keys of iris_dataset : {}".format(iris_dataset.keys()))

Keys of iris_dataset : dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [14]:
print("Type of data : {}".format(type(iris_dataset['data'])))

Type of data : <class 'numpy.ndarray'>


In [15]:
print("Shape of data : {}".format(iris_dataset['data'].shape))

Shape of data : (150, 4)


In [18]:
print("Target names : {}".format(iris_dataset['target_names']))

Target names : ['setosa' 'versicolor' 'virginica']


In [19]:
print("Features names {}".format(iris_dataset['feature_names']))

Features names ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [39]:
print("first five column of data : {}".format(iris_dataset['data'][:5]))

first five column of data : [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [21]:
print("Target : \n {}".format(iris_dataset['target']))
#O -> setosa
#1 -> versicolor
#2 -> virginica

Target : 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [24]:
#train dataset
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

In [26]:
print("X_train shape {}".format(X_train.shape))
print("y_train shape {}".format(y_train.shape))

X_train shape (112, 4)
y_train shape (112,)


In [27]:
print("X_test shape {}".format(X_test.shape))
print("y_test shape {}".format(y_test.shape))

X_test shape (38, 4)
y_test shape (38,)


In [33]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [34]:
y_pred = knn.predict(X_test)
print("Test set predictions : \n {}".format(y_pred))

Test set predictions : 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [37]:
print("Test set score : {:.2f}".format(np.mean(y_pred == y_test)))

Test set score : 0.97
